x-common: &common
    registry: mirror.gcr.io

services:
    database:
        image: mysql:8.0

        ports:
            - "3305:3306"
        networks:
            - app-network

    mailhog:
        image: mailhog/mailhog
        restart: unless-stopped
        ports:
            - "8025:8025"
            - "1025:1025"
        networks:
            - mail-network
            - app-network

volumes:
    db_data:
        driver: local

networks:
    app-network:
        driver: bridge
    mail-network:
        driver: bridge
